spring:
  application:
    name: psychologic
    password: ${SPRING_API_PASSWORD}

  datasource:
     url: ${SPRING_DB_URL}
     username: ${SPRING_DB_USERNAME}
     password: ${SPRING_DB_PASSWORD}
     driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true