spring:
  application:
    name: psychologic
    password: ${SPRING_API_PASSWORD}
    tokenLifetimeHours: 12

  datasource:
     url: ${SPRING_DB_URL}
     username: ${SPRING_DB_USERNAME}
     password: ${SPRING_DB_PASSWORD}
     driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

supabase:
  url: ${SUPABASE_STORAGE_URL}
  password: ${SUPABASE_PASSWORD}
  s3url: ${SUPABASE_S3_URL}
  s3Id: ${SUPABASE_S3_ID}
  s3Key: ${SUPABASE_S3_KEY}
