name: "Generar Especificación OpenAPI"

on:
  push:
    branches:
      - main
    paths:
      - 'spec/**'
  workflow_dispatch:

jobs:
  generate_spec:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout del repositorio"
        uses: actions/checkout@v2

      - name: Validar especificacion
        uses: mpetrunic/swagger-cli-action@v1.0.0
        with:
          command: "validate spec/main.yaml"

      - name: "Generar especificación OpenAPI"
        uses: mpetrunic/swagger-cli-action@v1.0.0
        with:
          command: "bundle -o spec.yaml -t yaml spec/main.yaml"

      - name: "Generar documentación con Swagger UI"
        uses: Legion2/swagger-ui-action@v1
        with:
            output: specs
            spec-file: spec.yaml
            GITHUB_TOKEN: ${{ secrets.EDSON_GITHUB_TOKEN }}

      - name: "Publicar documentación en GitHub Pages"
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.EDSON_GITHUB_TOKEN }}
            publish_dir: specs